# Generated by Django 4.2.15 on 2024-09-06 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_reactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reactions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reaction', to='blog.reaction'),
        ),
    ]
