# Generated by Django 4.2.15 on 2024-09-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_reaction_reaction_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction_option',
            field=models.IntegerField(choices=[(0, 'This is absolute complete waffle'), (1, 'This is pretty much waffle'), (2, 'I neither agree nor disagree with this waffle'), (3, 'I fully agree with this waffle')], null=True),
        ),
    ]
