# Generated by Django 4.2.15 on 2024-10-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='reactor',
        ),
        migrations.AlterUniqueTogether(
            name='userreaction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userreaction',
            name='post',
        ),
        migrations.RemoveField(
            model_name='userreaction',
            name='reaction',
        ),
        migrations.RemoveField(
            model_name='userreaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
        migrations.DeleteModel(
            name='UserReaction',
        ),
    ]
