# Generated by Django 4.2.15 on 2024-10-02 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reactions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reaction', to='blog.reaction'),
        ),
    ]
