# Generated by Django 4.2.15 on 2024-10-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_reactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reactions',
        ),
        migrations.AddField(
            model_name='post',
            name='reactions',
            field=models.ManyToManyField(blank=True, null=True, related_name='reaction', to='blog.reaction'),
        ),
    ]
