# Generated by Django 4.2.15 on 2024-10-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_reactions_post_reactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reactions',
            field=models.ManyToManyField(blank=True, related_name='reaction', to='blog.reaction'),
        ),
    ]
